### ISSUE TITLE
ANUBIX installation problem

### ISSUE THREAD

**Issue by TheJea** [korcsmarosgroup/ViralLink#1]
Hello, <br/>
I am trying to install ViralLink without a docker, on Mac os. My problem is that I couldn't install the ANUBIX package- I tried it with the given code in the ViralLink guide and also with the code on the Bitbucket/anubix website. It gives out the following message (in both cases): <br/>
`Downloading bitbucket repo sonnhammergroup/anubix@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://bitbucket.org/sonnhammergroup/anubix/get/HEAD.tar.gz' failed
`
<br/>
Could you help me?

**Comment by agathat** [comment]
Hello,

We have looked into this issue and it seems like it might be a problem with the order of downloading packages.

First download the Anubix repo from here: https://bitbucket.org/sonnhammergroup/anubix/src/master/
Then go to that directory (it is important), start R in that folder and install the packages in this order:

install.packages("dplyr")
install.packages("optimr")
install.packages("igraph")
BiocManager::install("Biobase")
install.packages("TailRank")
install.packages("ANUBIX_1.0.3.tar.gz", repos = NULL, type="source")

Hopefully this will solve your problem :)
