### ISSUE TITLE
Issue Running Pipeline

### ISSUE THREAD

**Issue by whbio** [korcsmarosgroup/ViralLink#2]
Hi, 

Having an issue getting the pipeline to run on OS X using the sample data and Docker. Always stops at:

*** [01:42:34] filter_network_expressed_genes.R is running... ***
WARNING: One of the parameters of the script does not exist: output_directory/1_process_expression_data/expressed_genes.txt

root@0035d1934ac0:/home/virallink#

Have tried several things to resolve the issue including downloading zip file again but always end up here, I do see that there's an error saying "Error: No such container: virallink", but I have Docker open when I start the pipeline and if I check Docker while the pipeline is running it says there is a container running named virallink...here is the complete run...Thank you!

[+] Building 1.7s (27/27) FINISHED                                              
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 119B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/selenium/standalone-chrome-deb  1.1s
 => [ 1/22] FROM docker.io/selenium/standalone-chrome-debug:3.13.0@sha256  0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 20.55kB                                       0.0s
 => CACHED [ 2/22] RUN apt-get update                                      0.0s
 => CACHED [ 3/22] RUN apt-get -y install default-jdk                      0.0s
 => CACHED [ 4/22] RUN echo '/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/ja  0.0s
 => CACHED [ 5/22] ADD *.sh /                                              0.0s
 => CACHED [ 6/22] RUN /bin/bash /install_base_layer.sh                    0.0s
 => CACHED [ 7/22] RUN mkdir /home/seluser/cytoscape                       0.0s
 => CACHED [ 8/22] WORKDIR /home/seluser/cytoscape                         0.0s
 => CACHED [ 9/22] RUN wget --progress=dot:giga --local-encoding=UTF-8 -v  0.0s
 => CACHED [10/22] RUN tar -zxvf cytoscape-3.7.0.tar.gz                    0.0s
 => CACHED [11/22] RUN rm cytoscape-3.7.0.tar.gz                           0.0s
 => CACHED [12/22] RUN echo "/home/seluser/cytoscape/cytoscape-unix-3.7.0  0.0s
 => CACHED [13/22] RUN chmod 777 /home/seluser/cytoscape/start.sh          0.0s
 => CACHED [14/22] WORKDIR /home/seluser                                   0.0s
 => CACHED [15/22] RUN sudo apt-get -y install git                         0.0s
 => CACHED [16/22] RUN git clone https://github.com/novnc/noVNC.git        0.0s
 => CACHED [17/22] RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/  0.0s
 => CACHED [18/22] RUN /bin/bash /install_python.sh                        0.0s
 => CACHED [19/22] RUN /bin/bash /install_r.sh                             0.0s
 => CACHED [20/22] ADD /pipeline /home/virallink/                          0.0s
 => CACHED [21/22] WORKDIR /home/virallink                                 0.0s
 => CACHED [22/22] ADD /entry_point.sh /opt/bin/entry_point.sh             0.0s
 => exporting to image                                                     0.3s
 => => exporting layers                                                    0.0s
 => => writing image sha256:cf52484f6c40047e1939c3e9782677774f5bb9cc9048e  0.2s
 => => naming to docker.io/library/virallink:latest                        0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Error: No such container: virallink
starting VNC server without password authentication
**** starting xvfb / selenium (pid=12)
**** Waiting xvfb...
**** fluxbox started
**** x11vnc started
**** cytoscape started
root@0035d1934ac0:/home/virallink# python3 virallink.py

*** ViralLink pipeline ***

*** Checking input parameters... ***
*** Input parameters are fine, starting... ***

*** Step 1/6 - PROCESS EXPRESSION DATA ***

*** [01:04:49] diff_expression_deseq2.R is running... ***
*** [01:35:43] diff_expression_deseq2.R finished successfully... ***

*** [01:35:43] filter_expression_gaussian.py is running... ***
*** [01:35:43] filter_expression_gaussian.py finished successfully... ***

*** Step 2/6 - PROCESS A PRIORI NETWORKS ***

*** [01:35:43] Downloading_omnipath_dorothea.R is running... ***
*** [01:42:34] Downloading_omnipath_dorothea.R finished successfully... ***

*** [01:42:34] filter_network_expressed_genes.R is running... ***
 WARNING: One of the parameters of the script does not exist: output_directory/1_process_expression_data/expressed_genes.txt

root@0035d1934ac0:/home/virallink#

**Comment by agathat** [comment]
Hi, Sorry for the delay coming back to you. 

So as I see, there is no problem here with the docker or any docker-related stuff. This message: "Error: No such container: virallink" is shows up, because there is no container, called virallink, which is currently running, when you start the pipeline. This message will come up in every case, when you start the pipeline and never used it before or used, but killed the container from the previous run.

The real problem is here: "WARNING: One of the parameters of the script does not exist: output_directory/1_process_expression_data/expressed_genes.txt"
The expressed_genes.txt file is missing and that is the reason why the pipeline stops working. It seems that this file was not properly generated in step 1  ' filter_expression_gaussian.py'. Without further information I cannot tell why this has happened I am afraid. Please check the log file for more details. It could be a problem with the python libraries or with the format of the input gene expression file / counts table. Please check that this is correct using information in the readme and the example input files (https://github.com/korcsmarosgroup/ViralLink). Thank you

**Comment by whbio** [comment]
Thank you! Would you be able to tell me how to access the appropriate log file or what further information might be helpful in finding a solution? Am familiar with finding log files in console but not in terminal. I did try the run again after cloning through the https link so I'd have a fresh download and was using the sample data for input but it stops at the same place. It looked like it was installing Python or Python components after I ran:

bash virallink.sh 

checked my Python version and have 3.8.3 installed...thanks!

Here's what I'm seeing:

bash virallink.sh
[+] Building 3.1s (27/27) FINISHED                                              
 => [internal] load build definition from Dockerfile                       0.6s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.6s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/selenium/standalone-chrome-deb  2.3s
 => [ 1/22] FROM docker.io/selenium/standalone-chrome-debug:3.13.0@sha256  0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 4.12kB                                        0.1s
 => CACHED [ 2/22] RUN apt-get update                                      0.0s
 => CACHED [ 3/22] RUN apt-get -y install default-jdk                      0.0s
 => CACHED [ 4/22] RUN echo '/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/ja  0.0s
 => CACHED [ 5/22] ADD *.sh /                                              0.0s
 => CACHED [ 6/22] RUN /bin/bash /install_base_layer.sh                    0.0s
 => CACHED [ 7/22] RUN mkdir /home/seluser/cytoscape                       0.0s
 => CACHED [ 8/22] WORKDIR /home/seluser/cytoscape                         0.0s
 => CACHED [ 9/22] RUN wget --progress=dot:giga --local-encoding=UTF-8 -v  0.0s
 => CACHED [10/22] RUN tar -zxvf cytoscape-3.7.0.tar.gz                    0.0s
 => CACHED [11/22] RUN rm cytoscape-3.7.0.tar.gz                           0.0s
 => CACHED [12/22] RUN echo "/home/seluser/cytoscape/cytoscape-unix-3.7.0  0.0s
 => CACHED [13/22] RUN chmod 777 /home/seluser/cytoscape/start.sh          0.0s
 => CACHED [14/22] WORKDIR /home/seluser                                   0.0s
 => CACHED [15/22] RUN sudo apt-get -y install git                         0.0s
 => CACHED [16/22] RUN git clone https://github.com/novnc/noVNC.git        0.0s
 => CACHED [17/22] RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/  0.0s
 => CACHED [18/22] RUN /bin/bash /install_python.sh                        0.0s
 => CACHED [19/22] RUN /bin/bash /install_r.sh                             0.0s
 => CACHED [20/22] ADD /pipeline /home/virallink/                          0.0s
 => CACHED [21/22] WORKDIR /home/virallink                                 0.0s
 => CACHED [22/22] ADD /entry_point.sh /opt/bin/entry_point.sh             0.0s
 => exporting to image                                                     0.2s
 => => exporting layers                                                    0.0s
 => => writing image sha256:371a915c329e01ae605bb27b90468c7fa2a3b4d87e5c9  0.0s
 => => naming to docker.io/library/virallink:latest                        0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Error: No such container: virallink
starting VNC server without password authentication
**** starting xvfb / selenium (pid=13)
**** Waiting xvfb...
**** Waiting xvfb...
**** fluxbox started
**** x11vnc started
**** cytoscape started
root@984a0951ec2e:/home/virallink# python3 virallink.py

*** ViralLink pipeline ***

*** Checking input parameters... ***
*** Input parameters are fine, starting... ***


*** Step 1/6 - PROCESS EXPRESSION DATA ***

*** [17:17:39] diff_expression_deseq2.R is running... ***
*** [17:48:15] diff_expression_deseq2.R finished successfully... ***

*** [17:48:15] filter_expression_gaussian.py is running... ***
*** [17:48:15] filter_expression_gaussian.py finished successfully... ***


*** Step 2/6 - PROCESS A PRIORI NETWORKS ***

*** [17:48:15] Downloading_omnipath_dorothea.R is running... ***
*** [17:55:05] Downloading_omnipath_dorothea.R finished successfully... ***

*** [17:55:05] filter_network_expressed_genes.R is running... ***
 WARNING: One of the parameters of the script does not exist: output_directory/1_process_expression_data/expressed_genes.txt

**Comment by agathat** [comment]
Hi, we will look into this issue with our test data and get back to you!

**Comment by agathat** [comment]
Thank you for your patience. My colleagues have looked into this and identified a new bug. They have pushed a fix to the repo. Please can you repull the repository and try to run it again? Let me know if you still have issues after this!

**Comment by whbio** [comment]
Thank you!!! Unfortunately there is still an issue. Was able to run it successfully till step six but got:

*** Step 6/6 - FUNCTIONAL ANALYSIS ***

*** [00:03:59] network_functional_analysis.R is running... ***
 WARNING: There was an error during the running! Please check the 'virallink.out' file for more details.

Checking the 'virallink.out" file I see:
 
Error in library(ReactomePA) : there is no package called ‘ReactomePA’
Execution halted

The complete run and the 'virallink.out' file are attached, thanks!

[Run 082421 .docx](https://github.com/korcsmarosgroup/ViralLink/files/7042861/Run.082421.docx)

[virallink.out 082421.docx](https://github.com/korcsmarosgroup/ViralLink/files/7042876/virallink.out.082421.docx)

**Comment by agathat** [comment]
Hi,

Sorry to hear you are still having issues. It seem that the container failed to install ReactomePA. Sometimes  the error **download length XXX != reported length YYY** indicates that an internet connectivity issue, so it might be that if you try again it will work. Also I have increased the timeout for the network_functional_analysis.R script which should allow it more time to download the package before timing out. I hope that it will now work for you.

**Comment by whbio** [comment]
Thank you!!! Still same issue with ReactomePA package but going to try a couple things on my end and will let you know. 

[Run August 25th 8pm.docx](https://github.com/korcsmarosgroup/ViralLink/files/7060795/Run.August.25th.8pm.docx)

**Comment by bbazsi41** [comment]
Hi,

Thank you for your patience. I am so sorry for having this problem. I found the bug and pushed a fix to the repo. I tested it and everything worked for me very well. I hope it will work for you as well wihtout any problem.
If you have still any issue after this, please just write to us and we will fix it as soon as possible.

Best wishes,
Balazs

**Comment by whbio** [comment]
Thank you! Unfortunately yes still having a problem with the ReactomePA package...tried twice today but no luck..second run is attached, thanks!

[Run #2 083121.docx](https://github.com/korcsmarosgroup/ViralLink/files/7086192/Run.2.083121.docx)

**Comment by bbazsi41** [comment]
Hi,

I am so sorry for hearing that. I pushed an other change to the repository. My colleague and I also tested this as well, and it worked for us without any problem. I hope it will work for you as well in this way.
On the other hand, as I see in the file, what you attached, you have a  problem with the download part, not with the installation itself.

This row means that you could not download the reactomedb package:

Error in download.file(url, destfile, method, mode = "wb", ...) : download from 'https://bioconductor.org/packages/3.13/data/annotation/src/contrib/reactome.db_1.76.0.tar.gz' failed

My suggestion is that maybe after the **bash virallink.sh** command you should try to install the ReactomePA package by manually.
When you get back the prompt and see something like this:
root@ed909fca2848:/home/virallink#

Then please just type `R` and you will enter the R terminal and please run this commands:

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

and then this:

if (!requireNamespace("ReactomePA", quietly = TRUE))
  BiocManager::install("ReactomePA", update = FALSE, ask = FALSE)
  
 The idea is that in this case we can check that you can install the ReactomePA R package by manually wihtout any problem or not.
 
 Please let me know if you have any problem or you need help.
 
 Best wishes,
 Balazs

**Comment by whbio** [comment]
Thank you! It looks like I can't manually install the ReactomePA package. from what I'm seeing: 

[Terminal Saved Output 090221 .docx](https://github.com/korcsmarosgroup/ViralLink/files/7102380/Terminal.Saved.Output.090221.docx)

**Comment by bbazsi41** [comment]
Thanks.
It is really strange, because this is the first error in the file what you attached (the same than in the docker container):
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://bioconductor.org/packages/3.13/data/annotation/src/contrib/reactome.db_1.76.0.tar.gz' failed
  
So my next suggestion is that please try to download this file via terminal with wget or curl. From this we can identify that you have some internet related problems or not, because it is really strange that you could not download this file. If you have time, please try this and let's see what will happen:
wget https://bioconductor.org/packages/3.13/data/annotation/src/contrib/reactome.db_1.76.0.tar.gz

Thanks and best wishes,
Balazs

**Comment by whbio** [comment]
Thank you! Yes, I was able to download it! BTW I installed Homebrew in order to obtain the wget command, it was not previously installed...I'll try to run the pipeline again and let you know how it works out, thanks!

**Comment by whbio** [comment]
Thanks for all your help! So here's where I'm at:

Was able to download the ReactomePA package using wget. As I mentioned I installed Homebrew to get the wget command. I was able to uncompress the ReactomePA file I downloaded so assume the download is ok.

[ReactomePA download with wget.docx](https://github.com/korcsmarosgroup/ViralLink/files/7117986/ReactomePA.download.with.wget.docx)

I'm still unable to manually install the ReactomePA package using the R commands you sent. Got the following message:

The downloaded source packages are in
	‘/tmp/RtmpjtaYTS/downloaded_packages’
Warning messages:
1: In .inet_warning(msg) : download of package ‘reactome.db’ failed
2: In .inet_warning(msg) :
  installation of package ‘ReactomePA’ had non-zero exit status
> 

[Manual install of ReactomePA attempt.docx](https://github.com/korcsmarosgroup/ViralLink/files/7117989/Manual.install.of.ReactomePA.attempt.docx)

Tried running the pipeline again but unable to do that and getting the same message indicating the problem is with the ReactomePA package. 

Happy to do anything I can to make this work and thanks so much for your help!

**Comment by bbazsi41** [comment]
Hi, sorry for still having this issue.

According to your log files, it seems to me that this is an internet issue, because after 300 seconds it automatically stops the download and that is why now I increased the timeout limit to 900 seconds , which has to be enough.

Now I would like to ask you to please pull the change from the repository and try to run the pipeline again. Or first you can try to start the R inside the docker container (after you get this kind of prompt: root@ed909fca2848:/home/virallink), then type R and try to install this package only with the same commands what I sent to you before. What it is easier for you. I hope it will solve your problem.
If it will still there, then please let me know and I will try to solve it.

Cheers,
Balazs

**Comment by whbio** [comment]
It's working! Thank you so much!!! I was able to run the pipeline and output the data and everything looks good!!! Thanks for all your help!!!

**Comment by bbazsi41** [comment]
Oh, that is great! You're welcome! I hope everything will be fine from now.
If there is no other issue, then I will close this comment tomorrow.
If you need any help in the future, then please let me know.

Cheers,
Balazs

**Comment by whbio** [comment]
Thank you Balazs! All the best!!!
